/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        academic: {
          surface: '#fff8f5',
          'surface-dim': '#f2d4bf',
          'surface-bright': '#fff8f5',
          'surface-container-lowest': '#ffffff',
          'surface-container-low': '#fff1e9',
          'surface-container': '#ffeadc',
          'surface-container-high': '#ffe3cf',
          'surface-container-highest': '#fbddc7',
          'on-surface': '#28180b',
          'on-surface-variant': '#564240',
          'inverse-surface': '#3f2d1e',
          'inverse-on-surface': '#ffede2',
          outline: '#8a7170',
          'outline-variant': '#ddc0be',
          'surface-tint': '#a33b3b',
          primary: '#5b040d',
          'on-primary': '#ffffff',
          'primary-container': '#7a1d20',
          'on-primary-container': '#ff8a86',
          'inverse-primary': '#ffb3af',
          secondary: '#256489',
          'on-secondary': '#ffffff',
          'secondary-container': '#9ad2fd',
          'on-secondary-container': '#195b80',
          tertiary: '#3e2500',
          'on-tertiary': '#ffffff',
          'tertiary-container': '#583a0f',
          'on-tertiary-container': '#cfa470',
          error: '#ba1a1a',
          'on-error': '#ffffff',
          'error-container': '#ffdad6',
          'on-error-container': '#93000a',
          'primary-fixed': '#ffdad7',
          'primary-fixed-dim': '#ffb3af',
          'on-primary-fixed': '#410005',
          'on-primary-fixed-variant': '#832426',
          'secondary-fixed': '#c9e6ff',
          'secondary-fixed-dim': '#94cdf8',
          'on-secondary-fixed': '#001e2f',
          'on-secondary-fixed-variant': '#004b6f',
          'tertiary-fixed': '#ffddb6',
          'tertiary-fixed-dim': '#ecbf88',
          'on-tertiary-fixed': '#2a1800',
          'on-tertiary-fixed-variant': '#5f4115',
          background: '#fff8f5',
          'on-background': '#28180b',
          'surface-variant': '#fbddc7',
        },
        brand: {
          primary: '#5b040d',
          secondary: '#cfa470',
          tertiary: '#256489',
          gold: {
            DEFAULT: '#cfa470',
            light: '#ecbf88',
            dark: '#583a0f',
          },
          maroon: {
            DEFAULT: '#5b040d',
            light: '#7a1d20',
            dark: '#410005',
          },
          blue: {
            DEFAULT: '#256489',
            light: '#9ad2fd',
            dark: '#195b80',
          },
          cream: {
            DEFAULT: '#fff8f5',
          },
        },
      },
      fontFamily: {
        sans: ['Manrope', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        display: ['Newsreader', 'serif'],
        mono: ['Inter', 'ui-monospace', 'monospace'],
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        xs: '4px',
        sm: '12px',
        md: '24px',
        lg: '48px',
        xl: '80px',
        gutter: '24px',
        margin: '32px',
      },
      boxShadow: {
        'academic': '0 4px 20px 0 rgba(40, 24, 11, 0.08)',
        'academic-lg': '0 10px 40px -10px rgba(40, 24, 11, 0.12)',
      }
    },
  },
  plugins: [],
}
